### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by R0GGER** [miroslavpejic85/p2p#1]
Microsoft warns for a trojan `Win32/Wacatac.B!ml`.

**Comment by miroslavpejic85** [comment]
Hello @R0GGER, 
You are right, however it could be seen as such, as it is an unknown app and doesn't have a digital signature. 
You can safely put it in exceptions in that case, and you can safely use it. I also leave you a scan on Virus Total: https://www.virustotal.com/gui/file/dd3e63dcf23f5892cd89e95b063e5b3fe0c41fc818a16d4f8d619bea4e3a7adb/detection Where I also left a comment that it is an open-source project. 
For any question or  doubt, I'm glad to help you.
Thanks

**Comment by miroslavpejic85** [comment]
I recompiled again an `p2p.exe` adding more info in the Assembly: https://github.com/miroslavpejic85/p2p/commit/a938e317a39b10b9dd84171470932ca93a27a162

![Assembly](https://user-images.githubusercontent.com/70838434/142946007-e0bb3d7b-7630-49a3-b000-45f0ba55d495.PNG)

Now seems is not detected as Trojan:Win32/Wacatac.B!ml O.o (No sense)
As I said, is a False positive detection. New scan here: https://www.virustotal.com/gui/file/fab1067fa9fb9e2f3f07d92cf774a2ad03dec455557f271f44208515ff09c8b5?nocache=1
Regards

**Comment by ocdtrekkie** [comment]
@miroslavpejic85 FYI, if this still occurs, or occurs again, you can submit your binary to https://www.microsoft.com/en-us/wdsi/filesubmission and specify you believe it is a false positive. Their security team can review it and fix the issue with their definitions. This is safer than asking users to exempt software from malware scanning, and costs you nothing, as no digital signature is required.

**Comment by miroslavpejic85** [comment]
Hello @ocdtrekkie, thank you so much for the tips!
