### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by CoolRoot** [miroslavpejic85/p2p#12]
Hello @miroslavpejic85

Great work, very interesting idea.

Is it possible that you provide pre-built binaries for the software somewhere?, for the ones who'd like to try but don't have Visual Studio to build and compile.

Thanks!

**Comment by miroslavpejic85** [comment]
Hello @CoolRoot, thank you.

I have to compile and submit it [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide) first, in order doesn't get detected as a false positive, being an open source project but probably unknown to them/av. In case, in the first forks of the project, you should find the executable. 

Have a nice day.

**Comment by Suleman-Elahi** [comment]
Any progress on binaries ? If your intention is not to release binaries, then at least can you provide build steps for other non dotnet ppl?

**Comment by miroslavpejic85** [comment]
Hello @Suleman-Elahi, check out: https://github.com/miroslavpejic85/p2p/issues/14#issuecomment-1001587883, thanks.

**Comment by Suleman-Elahi** [comment]
Okay I tried it. Any idea why this is happening?

![image](https://user-images.githubusercontent.com/24384996/153576254-d94caa4d-03cd-4966-8aa5-a939da2c104b.png)

**Comment by miroslavpejic85** [comment]
Ref:
- https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/Form1.cs#L159
- https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/StunClientEndPoint/StunClient.cs#L808

Try with other Stun: https://gist.github.com/zziuni/3741933
- https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/Form1.cs#L157

**Comment by Suleman-Elahi** [comment]
Thanks. I tried every server in the list..still gettign the same error.

**Comment by miroslavpejic85** [comment]
I'll make a change as soon as I can, I'll warn you, so you can try again ;) Thanks to you.

**Comment by miroslavpejic85** [comment]
Hello @Suleman-Elahi I added more stun server in this commit: https://github.com/miroslavpejic85/p2p/commit/171947c9789ef260edfcbf366cbd23b3ee21be79
Try now, Thank you.

**Comment by ilovefreesw** [comment]
Can try mine: https://github.com/ilovefreesw/p2p
