### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by basemind** [miroslavpejic85/p2p#13]
Hi, first of all, thanks for making this beautiful project open source. Everything works fine but after a long desktop connection, i get this error:
Receive Streaming: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at QuickLZ.Decompress(Byte[] source) in C:\myworkspace\vs2022\p2p\p2pconn\StreamingDesktop\QuickLZ.cs:line 293
   at p2pcopy.SenderReceiver.Run(Object conn) in C:\myworkspace\vs2022\p2p\p2pconn\SenderReceiver.cs:line 92

I used one pc, with two instance of the app. One in VS2017, one in VS2022.
![Capture](https://user-images.githubusercontent.com/29692630/146734966-93635bcd-aae4-4064-a4cf-b98a0f8174b1.PNG)

**Comment by miroslavpejic85** [comment]
Hello @basemind, thanks, Glad you like it. You can try to understand the problem ? I'm sure you can solve it.

**Comment by basemind** [comment]
I solved it i suppose, thanks for believing in me :) I put a zero to MemoryStream.
`using (MemoryStream MotionStream = new MemoryStream(100000000)) // 10000000`

In 1366x768 screen, connection cut after 6 min. After making MemoryStream ten times bigger, connection cut after 125 min.
