### ISSUE TITLE
windows defender report virus: Trojan:MSIL/AgentTesla.LQL!MTB

### ISSUE THREAD

**Issue by yangboyd** [miroslavpejic85/p2p#15]
windows defender report virus: Trojan:MSIL/AgentTesla.LQL!MTB for the compiled p2p.exe

**Comment by miroslavpejic85** [comment]
duplicate: https://github.com/miroslavpejic85/p2p/issues/1 issue, please read also [closed issues](https://github.com/miroslavpejic85/p2p/issues?q=is%3Aissue+is%3Aclosed) Thanks
