### ISSUE TITLE
Does it support Symmetric NAT firewalls?

### ISSUE THREAD

**Issue by yangboyd** [miroslavpejic85/p2p#16]
I thinks p2p supports full clone nat,  restricted clone nat,  port restricted NAT, But NOT  Symmetic Nat.

**Comment by miroslavpejic85** [comment]
Are you able to confirm? Thank you.

**Comment by miroslavpejic85** [comment]
More details here: https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/StunClientEndPoint/StunClient.cs#L1134
