### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by TheColonel2688** [miroslavpejic85/p2p#18]
I don't see any thing about security in the Readme. what Security features are in place? Is there End-To-End encryption?

**Comment by miroslavpejic85** [comment]
Hello @TheColonel2688, the data was protected by `AES256` encryption:
Encrypt: https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/SenderReceiver.cs#L234
Decrypt: https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/SenderReceiver.cs#L53
Regards
