### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [miroslavpejic85/p2p#19]
Hello, this project is currently missing the Code of Conduct. If you want to add that, then I would submit a PR with that. Please let me know what do you think about that.

**Comment by miroslavpejic85** [comment]
Hello @FahimFBA, To make it quick, you can fork the repo, make the changes, and send me a PR. Thanks so much.

**Comment by FahimFBA** [comment]
Please provide me an email address that would be enlisted in the Code of Conduct.

**Comment by miroslavpejic85** [comment]
But I didn't understand if you want to write the Code of Conduct of the p2p project (why?), or have you made some changes-improvements to the code and want to send me a PR? Can you explain me better what you mean for Code of Conduct? Thanks

**Comment by FahimFBA** [comment]
Oh! I see, let me provide the official info about it from the **GitHub Docs**:

> A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community.

It would make the project more community engaging.

**Comment by miroslavpejic85** [comment]
Maybe it might make sense if the project grows, what do you say, maybe I can create a channel on discord for this project (where we can discuss) and add the URL to join in the README. However, we already have the tools on GitHub to open the issues etc ...

**Comment by FahimFBA** [comment]
Yeah, that's also a great idea.
