### ISSUE TITLE
Trojan:MSIL/AgentTesla.LQL!MTB

### ISSUE THREAD

**Issue by kody-wen** [miroslavpejic85/p2p#24]
Build executive file was detected by Windows Defender as "Trojan:MSIL/AgentTesla.LQL!MTB".

Defender version:
Antimalware Client Version: 4.18.2203.5
Engine Version: 1.1.19100.5
Antivirus Version: 1.363.519.0
Antispyware Version: 1.363.519.0

**Comment by miroslavpejic85** [comment]
Duplicate: https://github.com/miroslavpejic85/p2p/issues/1 issue, please read also the [closed issues](https://github.com/miroslavpejic85/p2p/issues?q=is%3Aissue+is%3Aclosed) 
it's a `false positive detection`, thanks for the understanding. Cheers.
