### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by NewbridgeGareth** [miroslavpejic85/p2p#26]
Hi, 

Windows Defender does not like the executable when I build it and reports it as a virus. 
Trojan:MSIL/Dropper.CSC!MTB

Any ideas on what's going on here?

I can resolve it by allowing the exe file, but this is obv not a permanent or acceptable solution. 

Thanks

**Comment by miroslavpejic85** [comment]
Hi @NewbridgeGareth, 

Read please also the [closed issues](https://github.com/miroslavpejic85/p2p/issues?q=is%3Aissue+is%3Aclosed) - [discussions](https://github.com/miroslavpejic85/p2p/discussions/23), as I mentioned more time is a `false positive detection`.

If you have pleasure you can try to report it to Microsoft that is a open-source project, specifying that the executable is compiled from the source code.

Thanks for understanding.

**Comment by NewbridgeGareth** [comment]
Hi @miroslavpejic85 

Thanks for the quick response. 

I understand what you are saying. I think it is more that the actual behaviour of the application resembles a virus rather than it actually being one of course. 

I will have a look at the closed issues, apologies, I did not see them. 

Great work by the way! Seriously awesome!

I'm currently integrating it with SignalR in order to provide a relay server (Signalr) which maintains a list of PC's and their connected state. This shows up as a listview in the p2p app with an indicator image and the IP address. When you double click the item in the list view, it starts the local connection to the endpoint and then sends a message to the remote endpoint via SignalR relay requesting it to connect back to the machine that requested remote control. This then invokes the connect method but uses the IP and Port of the reuqesting PC. This negates the use of the text box for the endpoint and also the connect button. It's working nicely so far. :-)

**Comment by miroslavpejic85** [comment]
@NewbridgeGareth 

PS: If you have pleasure, you can share your implementation with us and submit a PR, that would be fantastic.
Describing what was done as above and you can put also some screenshots ;) Or if you have a fork of this modified project, you can share it with us.

Thanks

**Comment by martinweihrauch** [comment]
@NewbridgeGareth
Do you want to share your code regarding SignalR?
