### ISSUE TITLE
Rendezvous connection

### ISSUE THREAD

**Issue by CompuRoot** [miroslavpejic85/p2p#3]
First of all - **Thanks a lot for your project** !!!

It isn't an issue report, but suggestion to change `...rendezvous connection, it should be able to bypass **all** firewall rules etc` because it isn't true for **all** cases. In corporate environments, it pretty common that all outgoing connections are restricted by default on a border gateway and the only way to go "outside" is via proxy with authentication, so _TeamViewer_ also will get stuck in such environments unless explicitly enabled.

**Comment by miroslavpejic85** [comment]
Hello CompuRoot, It's a pleasure, hope it will be useful to someone, and thanks to you for sharing your experience about `corporate environments`, could be more correct to change in `most` :)
