### ISSUE TITLE
Trojan Horse detected

### ISSUE THREAD

**Issue by martinweihrauch** [miroslavpejic85/p2p#30]
Visual Studio won't run your code and messages to have found a trojan horse.
Same message from Windows Defender!

**Comment by martinweihrauch** [comment]
Trojan:MSIL/AgentTesla.LQL!MTB
file: p2pconn\obj\Debug\p2p.exe

**Comment by miroslavpejic85** [comment]
Hello @martinweihrauch, 
As already repeated a thousand times in closed issues, it is a false positive detection, as the app is not known by the AVs, without a digital signature. So put the folder on AV exception.
Please read also the closed issue before to post the new one!
Thank you for understanding.
BR. Miroslav

**Comment by miroslavpejic85** [comment]
PS: I'm added this in the README too: https://github.com/miroslavpejic85/p2p/blob/main/README.md#note

**Comment by martinweihrauch** [comment]
Sorry about my inquiry! 
I had never seen this before  so I was cautious.
All the best & thx for the work!

**Comment by miroslavpejic85** [comment]
Don't worry, you are welcome and thank you so much, I'm glad you like it.

**Comment by martinweihrauch** [comment]
Would the problem go away, if I rename some classes or maybe if I obfuscate the output?
Also, our company has a certificate, with which I could sign, if this helps...

**Comment by martinweihrauch** [comment]
BTW: it works, I just tested it.
A "disconnect" button would be nice. 
And if you click on the top right red cross, the application takes quite some time to disconnect.

**Comment by miroslavpejic85** [comment]
> Would the problem go away, if I rename some classes or maybe if I obfuscate the output?
> Also, our company has a certificate, with which I could sign, if this helps...

AVs are sensitive, sometimes it is enough to change only the name of a class or rename the methods in difficult words, or obfuscate the code with cryptographic techniques, which is not the case being open-source;) A digital signature would certainly solve.

**Comment by miroslavpejic85** [comment]
> BTW: it works, I just tested it.
> A "disconnect" button would be nice.
> And if you click on the top right red cross, the application takes quite some time to disconnect.

Good :) Any improvement PRs are always welcome!
