### ISSUE TITLE
Could not find a working STUN server

### ISSUE THREAD

**Issue by IgorManowar** [miroslavpejic85/p2p#45]
Hello friend, first of all thanks for your job. I've open the project in Visual Studio, compile and run it and get the message screen - Your external IP can't be obtained. Could not find a working STUN server.

The program shows:  stun.l.google.com 19302

Will you be so kind to help me with it? Thanks in advance.

**Comment by miroslavpejic85** [comment]
Hello @IgorManowar, 

Thank you for trying P2P Remote Desktop ;)

You can try with another Stun server, just add it in the lists.

![P2P-Stun](https://user-images.githubusercontent.com/70838434/205929917-1918ed99-8fd9-4cd2-a75f-86aa1004f497.png)

Check out also [this task](https://github.com/miroslavpejic85/p2p/issues/21), you can try with some in the old [hardcoded lists](https://github.com/miroslavpejic85/p2p/commit/171947c9789ef260edfcbf366cbd23b3ee21be79).

**Comment by ameaninglessname** [comment]
> Hello @IgorManowar,
> 
> Thank you for trying P2P Remote Desktop ;)
> 
> You can try with another Stun server, just add it in the lists.
> 
> ![P2P-Stun](https://user-images.githubusercontent.com/70838434/205929917-1918ed99-8fd9-4cd2-a75f-86aa1004f497.png)
> 
> Check out also [this task](https://github.com/miroslavpejic85/p2p/issues/21), you can try with some in the old [hardcoded lists](https://github.com/miroslavpejic85/p2p/commit/171947c9789ef260edfcbf366cbd23b3ee21be79).

It's there any convenient way to test stun server availability, I tried `p2p` last month and didn't succeed.
