### ISSUE TITLE
rdpwrap

### ISSUE THREAD

**Issue by test2a** [miroslavpejic85/p2p#5]
hey. does this need rdpwrap to have multiple users access a pc? can it even do multiple concurrent connections?

this looks nice but i would love to have multiple concurrent connections which currently require rdpwrap

**Comment by miroslavpejic85** [comment]
Hello test2a, not need, yes of course, you can execute `N instance of p2p.exe`, each instance generates a Lan and Wan endpoint to connects between peers. Imagine you want to assist N PCs at the same time, just open N instances of p2p.exe.

![P2P-multi-instances](https://user-images.githubusercontent.com/70838434/145202847-c7d3b716-531d-4f9b-b695-66758796a121.PNG)

![p2p-multi-connections](https://user-images.githubusercontent.com/70838434/145202922-fe8c9838-a2db-4f8e-adb1-0c5f2453d8f8.jpg)

**Comment by test2a** [comment]
@miroslavpejic85 thank you for answering. my question is different. if user b and user c want to connect to user A, will they get different "logins" inside user A? 

in windows, if multiple people for example join the same user from teamviewer, everyone uses 1 account. there is just one user which is controlled by everyone. RDP changes that by giving each user a "different user account"..

that is my question. can p2p connection be between different user accounts of user A?

**Comment by miroslavpejic85** [comment]
Hello @test2a you are welcome, Actually B-C can't connect to the same instance of A. 
There is no form of login, if user B-C wants to connect to the same user A, the user A must runs two instances of p2p.exe and communicates his endpoint to the two corresponding B-Cs. Once the connection is established, both B and C can assist user A at the same time, and the User A, in turn, can also assist User B-C. It is possible to make several cross combinations in both directions.
