### ISSUE TITLE
Error when Build

### ISSUE THREAD

**Issue by faniraja** [miroslavpejic85/p2p#51]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Form1.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	p2pconn			
![error]
(https://user-images.githubusercontent.com/1798265/215472323-92ce255f-eb5a-4e2b-93e9-ad4ba3c657b7.jpg)

**Comment by manfred-mueller** [comment]
...this is due to having not unblocked the downloaded zip file.

Open the file properties dialog of the downloaded zip file and place a check mark for the Unblock option on the General tab of the file properties dialog.

**Comment by ilovefreesw** [comment]
Use mine https://github.com/ilovefreesw/p2p

**Comment by miroslavpejic85** [comment]
> Open the file properties dialog of the downloaded zip file and place a check mark for the Unblock option on the General tab of the file properties dialog.

![Unblock](https://github.com/miroslavpejic85/p2p/assets/70838434/345e43a7-544f-432e-b459-a22c161645e4)
