### ISSUE TITLE
How to build self-hosted P2P intermediate server like Stun(http://stun.l.goolg.com) ?

### ISSUE THREAD

**Issue by Haoke98** [miroslavpejic85/p2p#56]
The Stun(http://stun.l.goolg.com) is not very friendly( not easy to reach) to the China mainland users. Is there any better solution?

**Comment by miroslavpejic85** [comment]
There are several open-source solutions available for building a STUN server. Here are a few options:

1. **Coturn**: Coturn is a free and open-source implementation of TURN and STUN server for VoIP and WebRTC. It's widely used and supports various platforms including Linux, macOS, and Windows. Coturn provides a flexible and feature-rich solution for NAT traversal in P2P communication.

   GitHub Repository: [Coturn](https://github.com/coturn/coturn)

2. **pystun**: If you prefer a solution in Python, `pystun` is a lightweight STUN client and server library. It's easy to use and can be integrated into your Python-based projects for handling STUN functionality.

   GitHub Repository: [pystun](https://github.com/jtriley/pystun)

3. **Stuntman**: Stuntman is an open-source STUN server implementation written in C. It's designed to be lightweight and efficient, suitable for embedding into other projects or running as a standalone server.

   GitHub Repository: [Stuntman](https://github.com/jselbie/stunserver)

4. **Node-STUN**: For Node.js developers, `node-stun` is a STUN server implementation written in JavaScript. It's designed to be lightweight and easy to integrate into Node.js applications.

   GitHub Repository: [node-stun](https://github.com/enobufs/stun)
   Available Stun to try: [public-stun](https://github.com/enobufs/stun?tab=readme-ov-file#public-stun-servers-that-work-with-this-stun-client)

These solutions provide a good starting point for building your own STUN server.
