### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Osiris-Team** [miroslavpejic85/p2p#64]
https://www.virustotal.com/gui/file/c83ac3cb2edbfe8c87230504f844f7f005d331e9be532694ef7f69450ea6c127
Windows defender flags the download as Trojan:Win32/Wacatac.B!ml
(also many others flag this is a similra virus)
Any ideas about the cause for this detection?
I assume its a false-positive. Is there a workaround to prevent this?

**Comment by miroslavpejic85** [comment]
As said in the README Note section: 

The app doesn't have a digital signature being an open source project, it may be detected as a false positive by AVs. When you compile it from the source code, just add the project in the exception. 

Thank you for understanding.
