### ISSUE TITLE
It gets detected as trojan :(

### ISSUE THREAD

**Issue by der-manu** [miroslavpejic85/p2p#7]
It gets detected as trojan :(
![Capture](https://user-images.githubusercontent.com/6383246/145200824-687f0788-6ab5-4197-ba3f-6b8277919204.PNG)

I really would love to see an OSS alternative to TV/Anydesk

**Comment by miroslavpejic85** [comment]
Hello der-manu, I have already answered [here](https://github.com/miroslavpejic85/p2p/issues/1#issuecomment-975937138) It's a `false positive detection`. Regards
