### ISSUE TITLE
connect between Windows 10&11

### ISSUE THREAD

**Issue by der-manu** [miroslavpejic85/p2p#8]
I gave it a try. I says Connected successfully. Chat works both ways but when trying to open a Desktop share (aither way) there is an error in the log:
user [01:19]: Start Sharing Desktop
user [01:19]: Stop Sharing Desktop: Arithmetic operation resulted in an overflow.
How can I provide detailed logs?

**Comment by miroslavpejic85** [comment]
Hello @der-manu, Maybe something related to the build x32-x64 bit, try recompiling the executable, do some cross-testings, let me know if persists? You can also execute it from the IDE, and print more logs [here](https://github.com/miroslavpejic85/p2p/blob/main/p2pconn/StreamingDesktop/RemoteDesktop.cs#L84). Thank you so much.
